[INFO_|03/11 21:33:32|OSTools.printMemoryUsage:1206] Memory-Mb: Max=3618.0, Total=244.0, Free=182.2, Used=61.8 [2%]
[INFO_|03/11 21:33:33|RTConfigContextListener.contextInitialized:223] java.awt.headless=false
[INFO_|03/11 21:33:40|Track._doWork:1329] Login Account/User: demo/admin [From 127.0.0.1]
[INFO_|03/11 21:33:40|Audit.userLoginOK:113] Login: Time=1426084420 Domain=default Account=demo User=admin IP=127.0.0.1
[INFO_|03/11 22:52:59|DBConnection.closeAllConnections:387] Closed all open DBConnections: 7
[INFO_|03/11 22:52:59|RTConfigContextListener.contextDestroyed:255] Remaining pool threads [0]: 0
[INFO_|03/11 22:52:59|RTConfigContextListener.contextDestroyed:258] ... Servlet Context destroyed: TrackWar
[INFO_|03/11 22:52:59|RTConfigContextListener.contextDestroyed:259] -----------------------------------------------
[INFO_|03/11 22:53:02|OSTools.printMemoryUsage:1206] Memory-Mb: Max=3618.0, Total=308.0, Free=151.4, Used=156.6 [4%]
[INFO_|03/11 22:53:02|RTConfigContextListener.contextInitialized:223] java.awt.headless=false
[INFO_|03/11 22:53:13|RTConfigContextListener.contextDestroyed:255] Remaining pool threads [0]: 0
[INFO_|03/11 22:53:13|RTConfigContextListener.contextDestroyed:258] ... Servlet Context destroyed: TrackWar
[INFO_|03/11 22:53:13|RTConfigContextListener.contextDestroyed:259] -----------------------------------------------
[INFO_|03/11 22:53:15|OSTools.printMemoryUsage:1206] Memory-Mb: Max=3618.0, Total=304.0, Free=157.4, Used=146.6 [4%]
[INFO_|03/11 22:53:16|RTConfigContextListener.contextInitialized:223] java.awt.headless=false
[INFO_|03/12 14:07:43|OSTools.printMemoryUsage:1206] Memory-Mb: Max=3618.0, Total=244.0, Free=194.1, Used=49.9 [1%]
[INFO_|03/12 14:07:44|RTConfigContextListener.contextInitialized:223] java.awt.headless=false
[WARN_|03/12 14:09:07|DBConnection.parseCommunicationsException:282] SQL(CommunicationsException) close/retry [0]: Connection Age 0 ms
[ERROR|03/12 14:09:08|Resource.getPrivateLabelPropertiesForHost:881] Exception: Error loading Resource: sysadmin/privatelabel.properties:localhost/track/Track
org.opengts.dbtools.DBException: Record existance Resource='sysadmin,privatelabel.properties:localhost/track/Track' [com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:414)
	at org.opengts.db.tables.Resource._getResource(Resource.java:546)
	at org.opengts.db.tables.Resource.getPrivateLabelPropertiesForHost(Resource.java:879)
	at org.opengts.war.track.Track._doWork_wrapper(Track.java:409)
	at org.opengts.war.track.Track.doGet(Track.java:311)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.opengts.war.track.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at org.opengts.dbtools.DBConnection.getConnection(DBConnection.java:662)
	at org.opengts.dbtools.DBConnection.createStatement(DBConnection.java:772)
	at org.opengts.dbtools.DBConnection._execute(DBConnection.java:875)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:843)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:796)
	at org.opengts.dbtools.DBRecordKey._exists(DBRecordKey.java:506)
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:410)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
	... 50 more
[WARN_|03/12 14:09:09|DBConnection.parseCommunicationsException:282] SQL(CommunicationsException) close/retry [0]: Connection Age 0 ms
[ERROR|03/12 14:09:10|Resource.getPrivateLabelPropertiesForHost:893] Exception: Error loading Resource: sysadmin/privatelabel.properties:localhost
org.opengts.dbtools.DBException: Record existance Resource='sysadmin,privatelabel.properties:localhost' [com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:414)
	at org.opengts.db.tables.Resource._getResource(Resource.java:546)
	at org.opengts.db.tables.Resource.getPrivateLabelPropertiesForHost(Resource.java:891)
	at org.opengts.war.track.Track._doWork_wrapper(Track.java:409)
	at org.opengts.war.track.Track.doGet(Track.java:311)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.opengts.war.track.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at org.opengts.dbtools.DBConnection.getConnection(DBConnection.java:662)
	at org.opengts.dbtools.DBConnection.createStatement(DBConnection.java:772)
	at org.opengts.dbtools.DBConnection._execute(DBConnection.java:875)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:843)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:796)
	at org.opengts.dbtools.DBRecordKey._exists(DBRecordKey.java:506)
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:410)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
	... 50 more
[WARN_|03/12 14:09:14|DBConnection.parseCommunicationsException:282] SQL(CommunicationsException) close/retry [0]: Connection Age 0 ms
[ERROR|03/12 14:09:15|Resource.getPrivateLabelPropertiesForHost:881] Exception: Error loading Resource: sysadmin/privatelabel.properties:localhost/track/Track
org.opengts.dbtools.DBException: Record existance Resource='sysadmin,privatelabel.properties:localhost/track/Track' [com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:414)
	at org.opengts.db.tables.Resource._getResource(Resource.java:546)
	at org.opengts.db.tables.Resource.getPrivateLabelPropertiesForHost(Resource.java:879)
	at org.opengts.war.track.Track._doWork_wrapper(Track.java:409)
	at org.opengts.war.track.Track.doPost(Track.java:322)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.opengts.war.track.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at org.opengts.dbtools.DBConnection.getConnection(DBConnection.java:662)
	at org.opengts.dbtools.DBConnection.createStatement(DBConnection.java:772)
	at org.opengts.dbtools.DBConnection._execute(DBConnection.java:875)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:843)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:796)
	at org.opengts.dbtools.DBRecordKey._exists(DBRecordKey.java:506)
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:410)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
	... 50 more
[WARN_|03/12 14:09:16|DBConnection.parseCommunicationsException:282] SQL(CommunicationsException) close/retry [0]: Connection Age 0 ms
[ERROR|03/12 14:09:17|Resource.getPrivateLabelPropertiesForHost:893] Exception: Error loading Resource: sysadmin/privatelabel.properties:localhost
org.opengts.dbtools.DBException: Record existance Resource='sysadmin,privatelabel.properties:localhost' [com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:414)
	at org.opengts.db.tables.Resource._getResource(Resource.java:546)
	at org.opengts.db.tables.Resource.getPrivateLabelPropertiesForHost(Resource.java:891)
	at org.opengts.war.track.Track._doWork_wrapper(Track.java:409)
	at org.opengts.war.track.Track.doPost(Track.java:322)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.opengts.war.track.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at org.opengts.dbtools.DBConnection.getConnection(DBConnection.java:662)
	at org.opengts.dbtools.DBConnection.createStatement(DBConnection.java:772)
	at org.opengts.dbtools.DBConnection._execute(DBConnection.java:875)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:843)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:796)
	at org.opengts.dbtools.DBRecordKey._exists(DBRecordKey.java:506)
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:410)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
	... 50 more
[WARN_|03/12 14:09:18|DBConnection.parseCommunicationsException:282] SQL(CommunicationsException) close/retry [0]: Connection Age 0 ms
[ERROR|03/12 14:09:19|Track._doWork:1196] Exception: Error reading Account: demo
org.opengts.dbtools.DBException: Record existance Account='demo' [com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:414)
	at org.opengts.db.tables.Account.getAccount(Account.java:3589)
	at org.opengts.war.track.Track._doWork(Track.java:1126)
	at org.opengts.war.track.Track._doWork_wrapper(Track.java:439)
	at org.opengts.war.track.Track.doPost(Track.java:322)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.opengts.war.track.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at org.opengts.dbtools.DBConnection.getConnection(DBConnection.java:662)
	at org.opengts.dbtools.DBConnection.createStatement(DBConnection.java:772)
	at org.opengts.dbtools.DBConnection._execute(DBConnection.java:875)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:843)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:796)
	at org.opengts.dbtools.DBRecordKey._exists(DBRecordKey.java:506)
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:410)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
	... 50 more
[WARN_|03/12 14:10:07|DBConnection.parseCommunicationsException:282] SQL(CommunicationsException) close/retry [0]: Connection Age 0 ms
[ERROR|03/12 14:10:08|Resource.getPrivateLabelPropertiesForHost:881] Exception: Error loading Resource: sysadmin/privatelabel.properties:localhost/track/Track
org.opengts.dbtools.DBException: Record existance Resource='sysadmin,privatelabel.properties:localhost/track/Track' [com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:414)
	at org.opengts.db.tables.Resource._getResource(Resource.java:546)
	at org.opengts.db.tables.Resource.getPrivateLabelPropertiesForHost(Resource.java:879)
	at org.opengts.war.track.Track._doWork_wrapper(Track.java:409)
	at org.opengts.war.track.Track.doGet(Track.java:311)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.opengts.war.track.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at org.opengts.dbtools.DBConnection.getConnection(DBConnection.java:662)
	at org.opengts.dbtools.DBConnection.createStatement(DBConnection.java:772)
	at org.opengts.dbtools.DBConnection._execute(DBConnection.java:875)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:843)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:796)
	at org.opengts.dbtools.DBRecordKey._exists(DBRecordKey.java:506)
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:410)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
	... 50 more
[WARN_|03/12 14:10:09|DBConnection.parseCommunicationsException:282] SQL(CommunicationsException) close/retry [0]: Connection Age 0 ms
[ERROR|03/12 14:10:10|Resource.getPrivateLabelPropertiesForHost:893] Exception: Error loading Resource: sysadmin/privatelabel.properties:localhost
org.opengts.dbtools.DBException: Record existance Resource='sysadmin,privatelabel.properties:localhost' [com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:414)
	at org.opengts.db.tables.Resource._getResource(Resource.java:546)
	at org.opengts.db.tables.Resource.getPrivateLabelPropertiesForHost(Resource.java:891)
	at org.opengts.war.track.Track._doWork_wrapper(Track.java:409)
	at org.opengts.war.track.Track.doGet(Track.java:311)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.opengts.war.track.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at org.opengts.dbtools.DBConnection.getConnection(DBConnection.java:662)
	at org.opengts.dbtools.DBConnection.createStatement(DBConnection.java:772)
	at org.opengts.dbtools.DBConnection._execute(DBConnection.java:875)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:843)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:796)
	at org.opengts.dbtools.DBRecordKey._exists(DBRecordKey.java:506)
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:410)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
	... 50 more
[INFO_|03/12 14:10:15|Track._doWork:1329] Login Account/User: demo/admin [From 127.0.0.1]
[INFO_|03/12 14:10:15|Audit.userLoginOK:113] Login: Time=1426144215 Domain=default Account=demo User=admin IP=127.0.0.1
[WARN_|03/12 14:21:28|OpenLayers.getGeozoneSupportedPointCount:199] Geozone type not supported: 2
[WARN_|03/12 14:21:41|OpenLayers.getGeozoneSupportedPointCount:199] Geozone type not supported: 2
[WARN_|03/12 14:22:21|OpenLayers.getGeozoneSupportedPointCount:199] Geozone type not supported: 2
[WARN_|03/12 14:22:31|OpenLayers.getGeozoneSupportedPointCount:199] Geozone type not supported: 2
[INFO_|03/12 14:34:32|Track._doWork:1329] Login Account/User: demo/admin [From 127.0.0.1]
[INFO_|03/12 14:34:32|Audit.userLoginOK:113] Login: Time=1426145672 Domain=default Account=demo User=admin IP=127.0.0.1
[INFO_|03/12 14:36:06|Track._doWork:1329] Login Account/User: demo/thaitest [From 127.0.0.1]
[INFO_|03/12 14:36:06|Audit.userLoginOK:113] Login: Time=1426145766 Domain=default Account=demo User=thaitest IP=127.0.0.1
[INFO_|03/12 14:36:39|Account.GetDemoAccountDeviceIDs:229] Demo Devices: demo|demo2
[INFO_|03/12 14:36:39|Account.GetDemoDeviceDateRange:253] Demo Device: demo/demo Date Rage 2014/10/20,2014/10/20
[WARN_|03/12 14:36:39|ReportSpreadsheet.GetExcelSpreadsheetClass:66] Excel interface not supported: java.lang.ClassNotFoundException: org.opengts.util.ExcelTools$Spreadsheet
[INFO_|03/12 14:36:41|DeviceInfo.writePage:1480] Allow New Device? Deny - per ACL
[INFO_|03/12 14:36:41|DeviceInfo.writePage:1513] Allow Delete Device? Deny - per ACL/New
[INFO_|03/12 14:36:48|DeviceInfo.writePage:1480] Allow New Device? Deny - per ACL
[INFO_|03/12 14:36:48|DeviceInfo.writePage:1513] Allow Delete Device? Deny - per ACL/New
[INFO_|03/12 14:37:05|DeviceInfo.writePage:1480] Allow New Device? Deny - per ACL
[INFO_|03/12 14:37:05|DeviceInfo.writePage:1513] Allow Delete Device? Deny - per ACL/New
[INFO_|03/12 14:37:07|DeviceInfo.writePage:1480] Allow New Device? Deny - per ACL
[INFO_|03/12 14:37:07|DeviceInfo.writePage:1513] Allow Delete Device? Deny - per ACL/New
[INFO_|03/12 14:40:19|Track._doWork:1329] Login Account/User: demo/admin [From 127.0.0.1]
[INFO_|03/12 14:40:19|Audit.userLoginOK:113] Login: Time=1426146019 Domain=default Account=demo User=admin IP=127.0.0.1
[INFO_|03/12 15:18:31|DeviceInfo._updateDeviceTable:1433] Nothing has changed for this Device ...
[INFO_|03/12 18:10:07|OSTools.printMemoryUsage:1206] Memory-Mb: Max=3618.0, Total=244.0, Free=182.8, Used=61.2 [2%]
[INFO_|03/12 18:10:08|RTConfigContextListener.contextInitialized:223] java.awt.headless=false
[WARN_|03/12 18:14:56|DBConnection.parseCommunicationsException:282] SQL(CommunicationsException) close/retry [0]: Connection Age 0 ms
[ERROR|03/12 18:14:57|Resource.getPrivateLabelPropertiesForHost:881] Exception: Error loading Resource: sysadmin/privatelabel.properties:localhost/track/Track
org.opengts.dbtools.DBException: Record existance Resource='sysadmin,privatelabel.properties:localhost/track/Track' [com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:414)
	at org.opengts.db.tables.Resource._getResource(Resource.java:546)
	at org.opengts.db.tables.Resource.getPrivateLabelPropertiesForHost(Resource.java:879)
	at org.opengts.war.track.Track._doWork_wrapper(Track.java:409)
	at org.opengts.war.track.Track.doGet(Track.java:311)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.opengts.war.track.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at org.opengts.dbtools.DBConnection.getConnection(DBConnection.java:662)
	at org.opengts.dbtools.DBConnection.createStatement(DBConnection.java:772)
	at org.opengts.dbtools.DBConnection._execute(DBConnection.java:875)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:843)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:796)
	at org.opengts.dbtools.DBRecordKey._exists(DBRecordKey.java:506)
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:410)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
	... 50 more
[WARN_|03/12 18:14:58|DBConnection.parseCommunicationsException:282] SQL(CommunicationsException) close/retry [0]: Connection Age 0 ms
[ERROR|03/12 18:14:59|Resource.getPrivateLabelPropertiesForHost:893] Exception: Error loading Resource: sysadmin/privatelabel.properties:localhost
org.opengts.dbtools.DBException: Record existance Resource='sysadmin,privatelabel.properties:localhost' [com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:414)
	at org.opengts.db.tables.Resource._getResource(Resource.java:546)
	at org.opengts.db.tables.Resource.getPrivateLabelPropertiesForHost(Resource.java:891)
	at org.opengts.war.track.Track._doWork_wrapper(Track.java:409)
	at org.opengts.war.track.Track.doGet(Track.java:311)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.opengts.war.track.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at org.opengts.dbtools.DBConnection.getConnection(DBConnection.java:662)
	at org.opengts.dbtools.DBConnection.createStatement(DBConnection.java:772)
	at org.opengts.dbtools.DBConnection._execute(DBConnection.java:875)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:843)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:796)
	at org.opengts.dbtools.DBRecordKey._exists(DBRecordKey.java:506)
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:410)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
	... 50 more
[WARN_|03/12 18:15:02|DBConnection.parseCommunicationsException:282] SQL(CommunicationsException) close/retry [0]: Connection Age 0 ms
[ERROR|03/12 18:15:03|Resource.getPrivateLabelPropertiesForHost:881] Exception: Error loading Resource: sysadmin/privatelabel.properties:localhost/track/Track
org.opengts.dbtools.DBException: Record existance Resource='sysadmin,privatelabel.properties:localhost/track/Track' [com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:414)
	at org.opengts.db.tables.Resource._getResource(Resource.java:546)
	at org.opengts.db.tables.Resource.getPrivateLabelPropertiesForHost(Resource.java:879)
	at org.opengts.war.track.Track._doWork_wrapper(Track.java:409)
	at org.opengts.war.track.Track.doPost(Track.java:322)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.opengts.war.track.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at org.opengts.dbtools.DBConnection.getConnection(DBConnection.java:662)
	at org.opengts.dbtools.DBConnection.createStatement(DBConnection.java:772)
	at org.opengts.dbtools.DBConnection._execute(DBConnection.java:875)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:843)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:796)
	at org.opengts.dbtools.DBRecordKey._exists(DBRecordKey.java:506)
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:410)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
	... 49 more
[WARN_|03/12 18:15:04|DBConnection.parseCommunicationsException:282] SQL(CommunicationsException) close/retry [0]: Connection Age 0 ms
[ERROR|03/12 18:15:05|Resource.getPrivateLabelPropertiesForHost:893] Exception: Error loading Resource: sysadmin/privatelabel.properties:localhost
org.opengts.dbtools.DBException: Record existance Resource='sysadmin,privatelabel.properties:localhost' [com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:414)
	at org.opengts.db.tables.Resource._getResource(Resource.java:546)
	at org.opengts.db.tables.Resource.getPrivateLabelPropertiesForHost(Resource.java:891)
	at org.opengts.war.track.Track._doWork_wrapper(Track.java:409)
	at org.opengts.war.track.Track.doPost(Track.java:322)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.opengts.war.track.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at org.opengts.dbtools.DBConnection.getConnection(DBConnection.java:662)
	at org.opengts.dbtools.DBConnection.createStatement(DBConnection.java:772)
	at org.opengts.dbtools.DBConnection._execute(DBConnection.java:875)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:843)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:796)
	at org.opengts.dbtools.DBRecordKey._exists(DBRecordKey.java:506)
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:410)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
	... 49 more
[WARN_|03/12 18:15:06|DBConnection.parseCommunicationsException:282] SQL(CommunicationsException) close/retry [0]: Connection Age 0 ms
[ERROR|03/12 18:15:07|Track._doWork:1196] Exception: Error reading Account: demo
org.opengts.dbtools.DBException: Record existance Account='demo' [com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:414)
	at org.opengts.db.tables.Account.getAccount(Account.java:3589)
	at org.opengts.war.track.Track._doWork(Track.java:1126)
	at org.opengts.war.track.Track._doWork_wrapper(Track.java:439)
	at org.opengts.war.track.Track.doPost(Track.java:322)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.opengts.war.track.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at org.opengts.dbtools.DBConnection.getConnection(DBConnection.java:662)
	at org.opengts.dbtools.DBConnection.createStatement(DBConnection.java:772)
	at org.opengts.dbtools.DBConnection._execute(DBConnection.java:875)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:843)
	at org.opengts.dbtools.DBConnection.execute(DBConnection.java:796)
	at org.opengts.dbtools.DBRecordKey._exists(DBRecordKey.java:506)
	at org.opengts.dbtools.DBRecordKey.exists(DBRecordKey.java:410)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
	... 49 more
[INFO_|03/12 20:17:02|Track._doWork:1329] Login Account/User: demo/admin [From 127.0.0.1]
[INFO_|03/12 20:17:03|Audit.userLoginOK:113] Login: Time=1426166223 Domain=default Account=demo User=admin IP=127.0.0.1
[WARN_|03/12 20:26:57|DCServerFactory.getServerConfigDescription:1612] DCS not found: gprmc
[INFO_|03/12 21:08:29|Track._doWork:1329] Login Account/User: demo/admin [From 127.0.0.1]
[INFO_|03/12 21:08:29|Audit.userLoginOK:113] Login: Time=1426169309 Domain=default Account=demo User=admin IP=127.0.0.1
[INFO_|03/13 11:25:20|OSTools.printMemoryUsage:1206] Memory-Mb: Max=3618.0, Total=244.0, Free=182.4, Used=61.6 [2%]
[INFO_|03/13 11:25:21|RTConfigContextListener.contextInitialized:223] java.awt.headless=false
[INFO_|03/13 11:29:48|Track._doWork:1329] Login Account/User: demo/admin [From 127.0.0.1]
[INFO_|03/13 11:29:48|Audit.userLoginOK:113] Login: Time=1426220988 Domain=default Account=demo User=admin IP=127.0.0.1
[WARN_|03/13 11:30:23|DCServerFactory.getServerConfigDescription:1612] DCS not found: gprmc
[INFO_|03/13 11:34:33|Track._doWork:1329] Login Account/User: demo/thaitest [From 127.0.0.1]
[INFO_|03/13 11:34:33|Audit.userLoginOK:113] Login: Time=1426221273 Domain=default Account=demo User=thaitest IP=127.0.0.1
[INFO_|03/13 13:38:37|OSTools.printMemoryUsage:1206] Memory-Mb: Max=3618.0, Total=436.0, Free=316.3, Used=119.7 [3%]
[INFO_|03/13 13:38:38|RTConfigContextListener.contextInitialized:223] java.awt.headless=false
[INFO_|03/13 13:47:05|Track._doWork:1329] Login Account/User: demo/thaitest [From 192.168.86.159]
[INFO_|03/13 13:47:06|Audit.userLoginOK:113] Login: Time=1426229226 Domain=default Account=demo User=thaitest IP=192.168.86.159
[INFO_|03/13 13:47:37|DeviceInfo.writePage:1480] Allow New Device? Deny - per ACL
[INFO_|03/13 13:47:37|DeviceInfo.writePage:1513] Allow Delete Device? Deny - per ACL/New
[WARN_|03/13 13:47:37|DCServerFactory.getServerConfigDescription:1612] DCS not found: gprmc
[INFO_|03/13 13:47:51|Track._doWork:1329] Login Account/User: demo/admin [From 192.168.86.159]
[INFO_|03/13 13:47:51|Audit.userLoginOK:113] Login: Time=1426229271 Domain=default Account=demo User=admin IP=192.168.86.159
[INFO_|03/13 13:51:04|DeviceInfo._updateDeviceTable:1433] Nothing has changed for this Device ...
[INFO_|03/13 14:06:26|Track._doWork:1329] Login Account/User: demo/admin [From 127.0.0.1]
[INFO_|03/13 14:06:26|Audit.userLoginOK:113] Login: Time=1426230386 Domain=default Account=demo User=admin IP=127.0.0.1
[INFO_|03/13 14:08:54|Track._doWork:1329] Login Account/User: demo/thaitest [From 127.0.0.1]
[INFO_|03/13 14:08:54|Audit.userLoginOK:113] Login: Time=1426230534 Domain=default Account=demo User=thaitest IP=127.0.0.1
[INFO_|03/13 14:16:03|DeviceInfo.writePage:1480] Allow New Device? Deny - per ACL
[INFO_|03/13 14:16:03|DeviceInfo.writePage:1513] Allow Delete Device? Deny - per ACL/New
[INFO_|03/13 14:16:05|DeviceInfo.writePage:1480] Allow New Device? Deny - per ACL
[INFO_|03/13 14:16:05|DeviceInfo.writePage:1513] Allow Delete Device? Deny - per ACL/New
[INFO_|03/13 14:16:17|Track._doWork:1329] Login Account/User: demo/admin [From 127.0.0.1]
[INFO_|03/13 14:16:17|Audit.userLoginOK:113] Login: Time=1426230977 Domain=default Account=demo User=admin IP=127.0.0.1
[INFO_|03/13 14:34:12|OSTools.printMemoryUsage:1206] Memory-Mb: Max=3618.0, Total=308.0, Free=193.5, Used=114.5 [3%]
[INFO_|03/13 14:34:13|RTConfigContextListener.contextInitialized:223] java.awt.headless=false
[INFO_|03/13 14:35:44|Track._doWork:1329] Login Account/User: demo/admin [From 127.0.0.1]
[INFO_|03/13 14:35:45|Audit.userLoginOK:113] Login: Time=1426232145 Domain=default Account=demo User=admin IP=127.0.0.1
[WARN_|03/13 14:41:57|DCServerFactory.getServerConfigDescription:1612] DCS not found: gprmc
[INFO_|03/13 15:32:29|Track._doWork:1329] Login Account/User: demo/admin [From 192.168.86.159]
[INFO_|03/13 15:32:29|Audit.userLoginOK:113] Login: Time=1426235549 Domain=default Account=demo User=admin IP=192.168.86.159
[INFO_|03/13 15:33:47|Track._doWork:1329] Login Account/User: demo/thaitest [From 192.168.86.159]
[INFO_|03/13 15:33:47|Audit.userLoginOK:113] Login: Time=1426235627 Domain=default Account=demo User=thaitest IP=192.168.86.159
[INFO_|03/13 15:34:05|Account.GetDemoAccountDeviceIDs:229] Demo Devices: demo|demo2
[WARN_|03/13 15:34:05|ReportSpreadsheet.GetExcelSpreadsheetClass:66] Excel interface not supported: java.lang.ClassNotFoundException: org.opengts.util.ExcelTools$Spreadsheet
[INFO_|03/13 15:34:09|ReportLayout.setReportPresentationClassName:294] Installing custom ReportPresentation class: org.opengts.war.report.presentation.ReportTable
[INFO_|03/13 15:35:13|Track._doWork:1329] Login Account/User: demo/admin [From 192.168.86.159]
[INFO_|03/13 15:35:13|Audit.userLoginOK:113] Login: Time=1426235713 Domain=default Account=demo User=admin IP=192.168.86.159
[INFO_|03/13 15:35:38|Track._doWork:1329] Login Account/User: demo/admin [From 192.168.86.159]
[INFO_|03/13 15:35:38|Audit.userLoginOK:113] Login: Time=1426235738 Domain=default Account=demo User=admin IP=192.168.86.159
[INFO_|03/13 15:35:56|Track._doWork:1329] Login Account/User: demo/thaitest [From 192.168.86.159]
[INFO_|03/13 15:35:56|Audit.userLoginOK:113] Login: Time=1426235756 Domain=default Account=demo User=thaitest IP=192.168.86.159
[INFO_|03/13 15:36:42|DeviceInfo.writePage:1480] Allow New Device? Deny - per ACL
[INFO_|03/13 15:36:43|DeviceInfo.writePage:1513] Allow Delete Device? Deny - per ACL/New
[INFO_|03/13 15:36:51|Track._doWork:1329] Login Account/User: demo/admin [From 192.168.86.159]
[INFO_|03/13 15:36:51|Audit.userLoginOK:113] Login: Time=1426235811 Domain=default Account=demo User=admin IP=192.168.86.159
[INFO_|03/13 15:37:00|Account.GetDemoAccountDeviceIDs:229] Demo Devices: demo|demo2
[INFO_|03/13 15:37:00|Account.GetDemoDeviceDateRange:253] Demo Device: demo/demo Date Rage 2014/10/20,2014/10/20
